# -*- coding: utf-8 -*-
"""tarea2_parte1.c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHLcDgnNyrdlwM-PSbE8VSeWuJ1yiOGu
"""

!gcc tarea2_parte1.c -o -lm tarea2_parte1.out

!gcc tarea2_parte1.c -o -lm tarea2_parte1.out

!gcc tarea2_parte1.c -o -lm tarea2_parte1.o